# Generated by Django 6.0.3 on 2026-03-28 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(blank=True, max_length=100)),
                ('start_year', models.IntegerField()),
                ('students_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='teachers/')),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='faculty.department')),
            ],
        ),
    ]
