# Generated by Django 6.0.3 on 2026-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hQlekjcwnmczbNqbRaUxHjUJ3f3yCagD', editable=False, max_length=32, unique=True),
        ),
    ]
